# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('sicDescription', models.CharField(max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('changeInCurrentAssets', models.BigIntegerField(null=True)),
                ('changeInCurrentLiabilities', models.BigIntegerField(null=True)),
                ('changeInInventories', models.BigIntegerField(null=True)),
                ('dividendsPaid', models.BigIntegerField(null=True)),
                ('capitalExpenditures', models.BigIntegerField(null=True)),
                ('cashFromFinancingActivities', models.BigIntegerField(null=True)),
                ('cashFromInvestingActivities', models.BigIntegerField(null=True)),
                ('cashFromOperatingActivities', models.BigIntegerField(null=True)),
                ('cfDepreciationAmortization', models.BigIntegerField(null=True)),
                ('changeInAccountsReceivable', models.BigIntegerField(null=True)),
                ('investmentChangesnet', models.BigIntegerField(null=True)),
                ('netChangeInCash', models.BigIntegerField(null=True)),
                ('totalAdjustments', models.BigIntegerField(null=True)),
                ('equityEarnings', models.BigIntegerField(null=True)),
                ('grossProfit', models.BigIntegerField(null=True)),
                ('interestExpense', models.BigIntegerField(null=True)),
                ('netIncome', models.BigIntegerField(null=True)),
                ('netIncomeApplicableToCommon', models.BigIntegerField(null=True)),
                ('researchDevelopmentExpense', models.BigIntegerField(null=True)),
                ('totalRevenue', models.BigIntegerField(null=True)),
                ('sellingGeneralAdministrativeExpenses', models.BigIntegerField(null=True)),
                ('commonStock', models.BigIntegerField(null=True)),
                ('cashAndCashEquivalents', models.BigIntegerField(null=True)),
                ('cashEquivalentsAndShortTermInvestments', models.BigIntegerField(null=True)),
                ('intangibleAssets', models.BigIntegerField(null=True)),
                ('goodwill', models.BigIntegerField(null=True)),
                ('inventoriesNet', models.BigIntegerField(null=True)),
                ('minorityInterest', models.BigIntegerField(null=True)),
                ('otherAssets', models.BigIntegerField(null=True)),
                ('otherLiabilities', models.BigIntegerField(null=True)),
                ('otherEquity', models.BigIntegerField(null=True)),
                ('otherCurrentLiabilities', models.BigIntegerField(null=True)),
                ('otherCurrentAssets', models.BigIntegerField(null=True)),
                ('preferredStock', models.BigIntegerField(null=True)),
                ('propertyPlantEquipmentnet', models.BigIntegerField(null=True)),
                ('retainedEarnings', models.BigIntegerField(null=True)),
                ('totalAssets', models.BigIntegerField(null=True)),
                ('totalCurrentAssets', models.BigIntegerField(null=True)),
                ('totalCurrentLiabilities', models.BigIntegerField(null=True)),
                ('totalLiabilities', models.BigIntegerField(null=True)),
                ('totalLongTermDebt', models.BigIntegerField(null=True)),
                ('totalReceivablesNet', models.BigIntegerField(null=True)),
                ('totalShortTermDebt', models.BigIntegerField(null=True)),
                ('totalStockholdersEquity', models.BigIntegerField(null=True)),
                ('treasuryStock', models.BigIntegerField(null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueCrawler.Company')),
            ],
        ),
    ]
