# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entityId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sicCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secform',
            name='currencyCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='secform',
            name='periodEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='secform',
            name='quarter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secform',
            name='usdConversionRate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='secform',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='sicDescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='period',
            field=models.CharField(default='', max_length=100),
        ),
    ]
