# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueCrawler', '0002_auto_20151227_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secform',
            name='capitalExpenditures',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cashAndCashEquivalents',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cashEquivalentsAndShortTermInvestments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cashFromFinancingActivities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cashFromInvestingActivities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cashFromOperatingActivities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='cfDepreciationAmortization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='changeInAccountsReceivable',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='changeInCurrentAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='changeInCurrentLiabilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='changeInInventories',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='commonStock',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='dividendsPaid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='equityEarnings',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='goodwill',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='grossProfit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='intangibleAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='interestExpense',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='inventoriesNet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='investmentChangesnet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='minorityInterest',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='netChangeInCash',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='netIncome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='netIncomeApplicableToCommon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='otherAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='otherCurrentAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='otherCurrentLiabilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='otherEquity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='otherLiabilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='preferredStock',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='propertyPlantEquipmentnet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='researchDevelopmentExpense',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='retainedEarnings',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='sellingGeneralAdministrativeExpenses',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalAdjustments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalCurrentAssets',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalCurrentLiabilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalLiabilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalLongTermDebt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalReceivablesNet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalRevenue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalShortTermDebt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='totalStockholdersEquity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secform',
            name='treasuryStock',
            field=models.CharField(default='', max_length=100),
        ),
    ]
